<?php
$title = 'Edit ecrire';
$this->headTitle($title);
?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <?php
 $form = $this->form;
 $form->setAttribute('action', $this->url(
     'ecrire',
     array(
         'action' => 'edit',
         'id'     => $this->id,
     )
 ));
 $form->prepare();


 
 
 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 echo $this->formRow($form->get('etu'));
 echo $this->formRow($form->get('cours'));
 echo $this->formRow($form->get('ex'));
 echo $this->formRow($form->get('note'));
 echo $this->formRow($form->get('maj'));
 
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();
 