<?php


 $title = 'My ecrires';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo $this->url('ecrire', array('action'=>'add'));?>">Add new ecrire</a>
 </p>

 <table class="table">
 <tr>
     <th>id_notes</th>
     <th>etudiant</th>
     <th>notes</th>
     <th>ex</th>
     <th>maj</th>
     
     
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($ecrires as $ecrire) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($ecrire->id);?></td>
     <td><?php echo $this->escapeHtml($ecrire->etu);?></td>
     <td><?php echo $this->escapeHtml($ecrire->note);?></td>
     <td><?php echo $this->escapeHtml($ecrire->ex);?></td>
     <td><?php echo $this->escapeHtml($ecrire->maj);?></td>
     <td>
         <a href="<?php echo $this->url('ecrire',
             array('action'=>'edit', 'id' => $ecrire->id));?>">Edit</a>
         <a href="<?php echo $this->url('ecrire',
             array('action'=>'delete', 'id' => $ecrire->id));?>">Delete</a>
             
   
     </td>
 </tr>
 <?php endforeach; ?>
 </table>
 